// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(RealDatabase))]
    [Migration("20231230104457_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Animals.Birds.Bird", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CanFly")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Bird");

                    b.HasData(
                        new
                        {
                            ID = new Guid("fa0f2ffd-cc7e-4d1e-800a-64e69040ab08"),
                            CanFly = false,
                            Name = "Chip"
                        },
                        new
                        {
                            ID = new Guid("1f65aebe-3c91-42e2-9483-7f5d852a42e8"),
                            CanFly = false,
                            Name = "Paulie"
                        },
                        new
                        {
                            ID = new Guid("4a1c2c51-f1a5-447d-84d1-58f1b5a1f744"),
                            CanFly = false,
                            Name = "Polly"
                        },
                        new
                        {
                            ID = new Guid("82c2ad03-ed9e-4ae1-adf1-d955f57faf77"),
                            CanFly = false,
                            Name = "Ace"
                        },
                        new
                        {
                            ID = new Guid("e08fb859-d0ec-4378-afbb-63b9330b92b3"),
                            CanFly = false,
                            Name = "Apollo"
                        },
                        new
                        {
                            ID = new Guid("254fb985-f914-460f-8b1a-a6297484484b"),
                            CanFly = false,
                            Name = "Daffy"
                        },
                        new
                        {
                            ID = new Guid("d8380ded-8622-4c0d-aedb-5b502b0057ad"),
                            CanFly = false,
                            Name = "Blue"
                        },
                        new
                        {
                            ID = new Guid("5757d04a-0933-4353-8439-8bdd8415e8af"),
                            CanFly = false,
                            Name = "Skye"
                        },
                        new
                        {
                            ID = new Guid("9cab531b-579f-4f48-9578-43d329788b0f"),
                            CanFly = false,
                            Name = "Jay"
                        },
                        new
                        {
                            ID = new Guid("ccd750ee-bcbf-47f7-a9f1-b570ee02eb12"),
                            CanFly = false,
                            Name = "Maverick"
                        });
                });

            modelBuilder.Entity("Domain.Models.Animals.Cats.Cat", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("LikesToPlay")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Cat");

                    b.HasData(
                        new
                        {
                            ID = new Guid("246e9545-2a8c-4134-976e-e565683d2c96"),
                            LikesToPlay = false,
                            Name = "Jack"
                        },
                        new
                        {
                            ID = new Guid("66af8755-5f17-4605-8cfb-bb870b9a5c06"),
                            LikesToPlay = false,
                            Name = "Signe"
                        },
                        new
                        {
                            ID = new Guid("4fe37411-51bf-4000-b4a0-e4771e316e5e"),
                            LikesToPlay = false,
                            Name = "Rose"
                        },
                        new
                        {
                            ID = new Guid("e9df5792-6beb-47d8-8950-ab44d4d8dd8f"),
                            LikesToPlay = false,
                            Name = "Mittens"
                        },
                        new
                        {
                            ID = new Guid("5a9bc831-1518-4b14-a426-24083e4ad7b8"),
                            LikesToPlay = false,
                            Name = "Fred"
                        },
                        new
                        {
                            ID = new Guid("9526cbb5-fcd1-4fbb-b35d-a1b13ef361af"),
                            LikesToPlay = false,
                            Name = "Molly"
                        },
                        new
                        {
                            ID = new Guid("c0a1aac2-8c49-4ebd-98f8-67a177f5d730"),
                            LikesToPlay = false,
                            Name = "Charlie"
                        },
                        new
                        {
                            ID = new Guid("dfff162b-be84-424f-b89b-e56310fba3ee"),
                            LikesToPlay = false,
                            Name = "Oscar"
                        },
                        new
                        {
                            ID = new Guid("cf580a3a-1345-44fe-9369-e6f64bf32183"),
                            LikesToPlay = false,
                            Name = "Tiger"
                        },
                        new
                        {
                            ID = new Guid("c1fd6019-3330-48f6-ba89-1f9c8cb06518"),
                            LikesToPlay = false,
                            Name = "Simba"
                        });
                });

            modelBuilder.Entity("Domain.Models.Animals.Dogs.Dog", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            ID = new Guid("5a0347f0-fce1-4938-a797-dbd07dd235ea"),
                            Name = "OldG"
                        },
                        new
                        {
                            ID = new Guid("0e2e253a-95c9-4c3d-a783-db9c9501d48f"),
                            Name = "NewG"
                        },
                        new
                        {
                            ID = new Guid("2db9bfdc-69c2-4e54-a5bc-f85ce516803d"),
                            Name = "Björn"
                        },
                        new
                        {
                            ID = new Guid("3da577be-0e55-4d8e-b8db-598ca8ecc30f"),
                            Name = "Patrik"
                        },
                        new
                        {
                            ID = new Guid("4de871ab-4f27-4ae7-a3af-92a7626bd065"),
                            Name = "Alfred"
                        },
                        new
                        {
                            ID = new Guid("4b11e739-4a5a-4029-bdbe-dee231987bd7"),
                            Name = "Stanley"
                        },
                        new
                        {
                            ID = new Guid("f4cfce40-f1ae-4922-86a4-884a1222abef"),
                            Name = "Rufus"
                        },
                        new
                        {
                            ID = new Guid("380301db-d6c0-4443-bc5f-d1a62ea87b47"),
                            Name = "Ludde"
                        },
                        new
                        {
                            ID = new Guid("ee16c6d8-8a8a-4c3b-b4e1-1bed16c1da1f"),
                            Name = "Felix"
                        },
                        new
                        {
                            ID = new Guid("1af64659-424f-4aad-953c-1a3a057fdc25"),
                            Name = "Peppe"
                        });
                });

            modelBuilder.Entity("Domain.Models.Users.User", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Authorized")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = new Guid("f54a9199-7214-495a-ae89-3634c7969ee2"),
                            Authorized = true,
                            Password = "admin",
                            Role = "admin",
                            Username = "admin"
                        },
                        new
                        {
                            ID = new Guid("12345678-1234-5678-1234-567812345674"),
                            Authorized = true,
                            Password = "password",
                            Role = "admin",
                            Username = "testUser2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
