// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(RealDatabase))]
    [Migration("20231230112949_AnimalUserTest1")]
    partial class AnimalUserTest1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Animals.Birds.Bird", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CanFly")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Bird");

                    b.HasData(
                        new
                        {
                            ID = new Guid("4cfd5f16-4fc1-4b71-8bab-f6d22a791bad"),
                            CanFly = false,
                            Name = "Chip"
                        },
                        new
                        {
                            ID = new Guid("58d02309-9542-458b-8c16-f99070f02462"),
                            CanFly = false,
                            Name = "Paulie"
                        },
                        new
                        {
                            ID = new Guid("3ebf67c4-2621-406c-bc10-00fda4e76bf7"),
                            CanFly = false,
                            Name = "Polly"
                        },
                        new
                        {
                            ID = new Guid("97071c12-8452-48f4-8c13-227dcc6f8c04"),
                            CanFly = false,
                            Name = "Ace"
                        },
                        new
                        {
                            ID = new Guid("afe8df4a-b612-48a0-91b0-e82d52e6f175"),
                            CanFly = false,
                            Name = "Apollo"
                        },
                        new
                        {
                            ID = new Guid("d73aca67-8d27-4a88-a577-768185b08844"),
                            CanFly = false,
                            Name = "Daffy"
                        },
                        new
                        {
                            ID = new Guid("4ec7d216-ed10-4920-b54b-79c8098f8efe"),
                            CanFly = false,
                            Name = "Blue"
                        },
                        new
                        {
                            ID = new Guid("9af5cf28-505a-43a4-86be-ea70c014a862"),
                            CanFly = false,
                            Name = "Skye"
                        },
                        new
                        {
                            ID = new Guid("e148aebc-98c0-4448-8dc1-757a08b9659e"),
                            CanFly = false,
                            Name = "Jay"
                        },
                        new
                        {
                            ID = new Guid("94b416fb-7d9d-4c6b-8337-860d87792658"),
                            CanFly = false,
                            Name = "Maverick"
                        });
                });

            modelBuilder.Entity("Domain.Models.Animals.Cats.Cat", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("LikesToPlay")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Cat");

                    b.HasData(
                        new
                        {
                            ID = new Guid("e4bdf6f1-e7b1-4e15-a504-a2d57c9cb844"),
                            LikesToPlay = false,
                            Name = "Jack"
                        },
                        new
                        {
                            ID = new Guid("7e6bd537-bcd8-4d29-a9e9-53eef493206e"),
                            LikesToPlay = false,
                            Name = "Signe"
                        },
                        new
                        {
                            ID = new Guid("3f628163-62b0-436a-922b-800f0f1d9b7c"),
                            LikesToPlay = false,
                            Name = "Rose"
                        },
                        new
                        {
                            ID = new Guid("a446eb46-8c81-4ba3-9aba-a6df905e8bcd"),
                            LikesToPlay = false,
                            Name = "Mittens"
                        },
                        new
                        {
                            ID = new Guid("8bf5e3c4-6945-48ff-87bd-3be1045f5c80"),
                            LikesToPlay = false,
                            Name = "Fred"
                        },
                        new
                        {
                            ID = new Guid("acfb6556-999a-4b66-b515-1d80e8523325"),
                            LikesToPlay = false,
                            Name = "Molly"
                        },
                        new
                        {
                            ID = new Guid("1e12ff71-ac41-4c64-8dcb-246a10bb7432"),
                            LikesToPlay = false,
                            Name = "Charlie"
                        },
                        new
                        {
                            ID = new Guid("9fad63db-971b-4a34-919d-2d29a16aaa69"),
                            LikesToPlay = false,
                            Name = "Oscar"
                        },
                        new
                        {
                            ID = new Guid("9671240d-0081-4dd9-9f85-de1091c60ff0"),
                            LikesToPlay = false,
                            Name = "Tiger"
                        },
                        new
                        {
                            ID = new Guid("cc67d7cd-84be-46b4-8016-73eecdceea23"),
                            LikesToPlay = false,
                            Name = "Simba"
                        });
                });

            modelBuilder.Entity("Domain.Models.Animals.Dogs.Dog", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            ID = new Guid("359e2e4b-a07e-4db2-9b4f-2284a6a1b894"),
                            Name = "OldG"
                        },
                        new
                        {
                            ID = new Guid("c9bbbee9-818f-4989-a80b-af882e5740de"),
                            Name = "NewG"
                        },
                        new
                        {
                            ID = new Guid("822875f8-ab87-4f30-b863-f3f1b2036319"),
                            Name = "Björn"
                        },
                        new
                        {
                            ID = new Guid("fdd112c5-569e-4374-b017-60d8afc68129"),
                            Name = "Patrik"
                        },
                        new
                        {
                            ID = new Guid("1606366f-0da5-48b3-9c19-625e590e00af"),
                            Name = "Alfred"
                        },
                        new
                        {
                            ID = new Guid("32f0f92c-0100-4719-890d-786aff01182f"),
                            Name = "Stanley"
                        },
                        new
                        {
                            ID = new Guid("df6e8c3b-3be6-44f8-8d6b-b42e12b9acfd"),
                            Name = "Rufus"
                        },
                        new
                        {
                            ID = new Guid("db21abd9-472f-4b14-bdd9-d144ce7f2eb3"),
                            Name = "Ludde"
                        },
                        new
                        {
                            ID = new Guid("f0ac1eeb-5e4e-435d-9a39-a54f12397609"),
                            Name = "Felix"
                        },
                        new
                        {
                            ID = new Guid("7095cbf9-50c3-4d07-aae8-e936797f7dcf"),
                            Name = "Peppe"
                        });
                });

            modelBuilder.Entity("Domain.Models.Users.User", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Authorized")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = new Guid("6e6ac3fb-ef4a-4d31-9d43-ac90e9a7516a"),
                            Authorized = true,
                            Password = "admin",
                            Role = "admin",
                            Username = "admin"
                        },
                        new
                        {
                            ID = new Guid("12345678-1234-5678-1234-567812345674"),
                            Authorized = true,
                            Password = "password",
                            Role = "admin",
                            Username = "testUser2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
