// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(RealDatabase))]
    [Migration("20240103133256_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnimalUser", b =>
                {
                    b.Property<Guid>("AnimalsAnimalID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsersID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AnimalsAnimalID", "UsersID");

                    b.HasIndex("UsersID");

                    b.ToTable("AnimalUser");
                });

            modelBuilder.Entity("Domain.Models.AnimalUsers.AnimalUser", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnimalID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserID");

                    b.ToTable("AnimalUsers");
                });

            modelBuilder.Entity("Domain.Models.Animals.Animal", b =>
                {
                    b.Property<Guid>("AnimalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnimalID");

                    b.ToTable("Animal");
                });

            modelBuilder.Entity("Domain.Models.Animals.Birds.Bird", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CanFly")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Birds");

                    b.HasData(
                        new
                        {
                            ID = new Guid("af7915b3-1f34-48b9-aed0-edd93965e1c9"),
                            CanFly = false,
                            Name = "Chip"
                        },
                        new
                        {
                            ID = new Guid("a64972a9-f3dd-4913-9eea-2224f30035cf"),
                            CanFly = false,
                            Name = "Paulie"
                        },
                        new
                        {
                            ID = new Guid("52b4eb8e-9aa9-44bb-bf44-882cede8b1c6"),
                            CanFly = false,
                            Name = "Polly"
                        },
                        new
                        {
                            ID = new Guid("3b6c49dd-0e7d-4f4a-9645-ba4254f19591"),
                            CanFly = false,
                            Name = "Ace"
                        },
                        new
                        {
                            ID = new Guid("22415db2-cbc1-4097-a20a-f372a54f9ae3"),
                            CanFly = false,
                            Name = "Apollo"
                        },
                        new
                        {
                            ID = new Guid("68a249fa-43fe-4034-afbe-350b901d1196"),
                            CanFly = false,
                            Name = "Daffy"
                        },
                        new
                        {
                            ID = new Guid("d266b965-8f63-430e-b816-4832a10ab9fc"),
                            CanFly = false,
                            Name = "Blue"
                        },
                        new
                        {
                            ID = new Guid("7fbb291e-b4d0-4c0a-83e2-0e4db60972a2"),
                            CanFly = false,
                            Name = "Skye"
                        },
                        new
                        {
                            ID = new Guid("d9babcfe-fb4c-4483-97a3-92e8bd7c136f"),
                            CanFly = false,
                            Name = "Jay"
                        },
                        new
                        {
                            ID = new Guid("5eeefd5e-8a34-4239-969b-d4e69342effe"),
                            CanFly = false,
                            Name = "Maverick"
                        });
                });

            modelBuilder.Entity("Domain.Models.Animals.Cats.Cat", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("LikesToPlay")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            ID = new Guid("fd187582-c76b-4d33-863f-95f303185a95"),
                            LikesToPlay = false,
                            Name = "Jack"
                        },
                        new
                        {
                            ID = new Guid("9241866f-459b-4926-9883-793ff1bd8ff1"),
                            LikesToPlay = false,
                            Name = "Signe"
                        },
                        new
                        {
                            ID = new Guid("496d09b5-c67f-4a88-8696-e6f4d749f8c6"),
                            LikesToPlay = false,
                            Name = "Rose"
                        },
                        new
                        {
                            ID = new Guid("528fae60-1c86-4825-b315-bdd6db294a4e"),
                            LikesToPlay = false,
                            Name = "Mittens"
                        },
                        new
                        {
                            ID = new Guid("c23168a4-e238-4c2c-8179-710b4376bc31"),
                            LikesToPlay = false,
                            Name = "Fred"
                        },
                        new
                        {
                            ID = new Guid("fc7ce72f-b39f-4f41-9445-b3909ee41a6d"),
                            LikesToPlay = false,
                            Name = "Molly"
                        },
                        new
                        {
                            ID = new Guid("edd464ee-4c70-4420-a86e-0cf5cde842c6"),
                            LikesToPlay = false,
                            Name = "Charlie"
                        },
                        new
                        {
                            ID = new Guid("d4562dea-1d3c-4f49-900e-f5206d5e3ad6"),
                            LikesToPlay = false,
                            Name = "Oscar"
                        },
                        new
                        {
                            ID = new Guid("c72ee6d4-66ee-45e2-a9c3-4b477b54bbfa"),
                            LikesToPlay = false,
                            Name = "Tiger"
                        },
                        new
                        {
                            ID = new Guid("c50a74f3-ca5f-461b-a6c0-9ba773902318"),
                            LikesToPlay = false,
                            Name = "Simba"
                        });
                });

            modelBuilder.Entity("Domain.Models.Animals.Dogs.Dog", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            ID = new Guid("d0a9d8e6-b2ca-4205-9e9e-abb60eef9381"),
                            Name = "OldG"
                        },
                        new
                        {
                            ID = new Guid("dde412ec-1f63-4f95-8a8f-8c1c03054ea4"),
                            Name = "NewG"
                        },
                        new
                        {
                            ID = new Guid("49165a33-a67f-489e-8da0-1f058d2d6fae"),
                            Name = "Björn"
                        },
                        new
                        {
                            ID = new Guid("efe0d39a-0eb9-46e9-b564-d7e92f4742d8"),
                            Name = "Patrik"
                        },
                        new
                        {
                            ID = new Guid("86782122-154c-42b8-a480-42bafca678bd"),
                            Name = "Alfred"
                        },
                        new
                        {
                            ID = new Guid("95a6f178-ccdb-411d-9ea6-9f102ffe2843"),
                            Name = "Stanley"
                        },
                        new
                        {
                            ID = new Guid("0f67d6f3-a582-4a59-8d9c-64cf29ba27f0"),
                            Name = "Rufus"
                        },
                        new
                        {
                            ID = new Guid("60805ceb-fa1d-4aa3-b642-2bee3196db49"),
                            Name = "Ludde"
                        },
                        new
                        {
                            ID = new Guid("a415a527-63e7-446f-8c84-d574e725acde"),
                            Name = "Felix"
                        },
                        new
                        {
                            ID = new Guid("c57b02f2-8a42-4955-acc4-1b3b51d2ae6c"),
                            Name = "Peppe"
                        });
                });

            modelBuilder.Entity("Domain.Models.Users.User", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Authorized")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = new Guid("08f08c1f-fd93-4a36-be54-3f3efc27e837"),
                            Authorized = true,
                            Password = "admin",
                            Role = "admin",
                            Username = "admin"
                        },
                        new
                        {
                            ID = new Guid("12345678-1234-5678-1234-567812345674"),
                            Authorized = true,
                            Password = "password",
                            Role = "admin",
                            Username = "testUser2"
                        });
                });

            modelBuilder.Entity("AnimalUser", b =>
                {
                    b.HasOne("Domain.Models.Animals.Animal", null)
                        .WithMany()
                        .HasForeignKey("AnimalsAnimalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UsersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
