// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(RealDatabase))]
    [Migration("20240117102422_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.AnimalUsers.AnimalUser", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnimalID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Key");

                    b.HasIndex("AnimalID");

                    b.HasIndex("UserID");

                    b.ToTable("AnimalUsers");
                });

            modelBuilder.Entity("Domain.Models.Animals.Animal", b =>
                {
                    b.Property<Guid>("AnimalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnimalID");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalID = new Guid("e7775aaf-f27c-469e-b17d-0c88590e1fc4"),
                            Name = "OldG",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalID = new Guid("aa9cd7c2-a702-4658-a09a-5f4f622873e2"),
                            Name = "NewG",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalID = new Guid("dd622008-e534-46d2-8df8-6fa330f16ebb"),
                            Name = "Björn",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalID = new Guid("25925cfb-a43a-490d-852d-69f8a085d0fb"),
                            Name = "Patrik",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalID = new Guid("d0278d8a-e841-4639-841a-4d9b5a5935de"),
                            Name = "Alfred",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalID = new Guid("57bb1c98-5da1-4552-aa00-921bdb53e542"),
                            Name = "Stanley",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalID = new Guid("753b16a5-479e-4528-a75d-5e98033cd0c1"),
                            Name = "Rufus",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalID = new Guid("3d5fa03c-a75c-4eff-81c4-d0e1c7f82ff3"),
                            Name = "Ludde",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalID = new Guid("5c65250c-21ae-4e92-b6b7-2a42f311edc3"),
                            Name = "Felix",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalID = new Guid("f7b4f4ae-19d2-4fd6-bfcc-536921b3a867"),
                            Name = "Peppe",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalID = new Guid("01df08f7-f0e8-433b-aed0-c426ae257fcc"),
                            Name = "Jack",
                            Type = "Cat"
                        },
                        new
                        {
                            AnimalID = new Guid("37a7f1e7-7c39-4a9f-a72b-d5022d61c021"),
                            Name = "Signe",
                            Type = "Cat"
                        },
                        new
                        {
                            AnimalID = new Guid("1e34fb48-58b3-4685-a38b-1b381fa07e22"),
                            Name = "Rose",
                            Type = "Cat"
                        },
                        new
                        {
                            AnimalID = new Guid("7da9bbfa-0ff4-4758-941b-55dedda0aca7"),
                            Name = "Mittens",
                            Type = "Cat"
                        },
                        new
                        {
                            AnimalID = new Guid("dc1f1b5a-50ae-4b21-ba80-7919403d2634"),
                            Name = "Fred",
                            Type = "Cat"
                        },
                        new
                        {
                            AnimalID = new Guid("2112ef42-3c65-400b-aa15-2891b4fbb6f0"),
                            Name = "Molly",
                            Type = "Cat"
                        },
                        new
                        {
                            AnimalID = new Guid("d0ddb4a7-9369-4b3f-9c2a-5b3e282235ef"),
                            Name = "Charlie",
                            Type = "Cat"
                        },
                        new
                        {
                            AnimalID = new Guid("33d22b2d-db29-482a-9c87-225ab75592ed"),
                            Name = "Oscar",
                            Type = "Cat"
                        },
                        new
                        {
                            AnimalID = new Guid("5cb27aea-7288-46a2-80dc-1715a6d35c29"),
                            Name = "Tiger",
                            Type = "Cat"
                        },
                        new
                        {
                            AnimalID = new Guid("a4ba4856-b64b-4697-adde-516c9f856fa5"),
                            Name = "Simba",
                            Type = "Cat"
                        },
                        new
                        {
                            AnimalID = new Guid("0303504c-ec24-401a-860c-1ac0ae9f12ff"),
                            Name = "Chip",
                            Type = "Bird"
                        },
                        new
                        {
                            AnimalID = new Guid("3deb994b-b559-40cf-8003-40d644fcfc8a"),
                            Name = "Paulie",
                            Type = "Bird"
                        },
                        new
                        {
                            AnimalID = new Guid("6ccc4bd2-ff46-45ed-8a71-03a4318714e8"),
                            Name = "Polly",
                            Type = "Bird"
                        },
                        new
                        {
                            AnimalID = new Guid("b18205d4-17ca-4233-93dd-8923154eeba4"),
                            Name = "Ace",
                            Type = "Bird"
                        },
                        new
                        {
                            AnimalID = new Guid("f1233b7a-ba0e-464f-8633-6ddcd45962b9"),
                            Name = "Apollo",
                            Type = "Bird"
                        },
                        new
                        {
                            AnimalID = new Guid("f56a5dc5-35df-4f8a-b255-294fbd812891"),
                            Name = "Daffy",
                            Type = "Bird"
                        },
                        new
                        {
                            AnimalID = new Guid("24dc68c6-6980-46f6-b23f-e3abccc0a0f1"),
                            Name = "Blue",
                            Type = "Bird"
                        },
                        new
                        {
                            AnimalID = new Guid("221d53e4-1e0f-44a7-93a0-dd14dc8104b3"),
                            Name = "Skye",
                            Type = "Bird"
                        },
                        new
                        {
                            AnimalID = new Guid("2dbbd568-78e0-42ff-a675-bf268adf598e"),
                            Name = "Jay",
                            Type = "Bird"
                        },
                        new
                        {
                            AnimalID = new Guid("7a50bfdc-e200-41e8-9769-e70f77147cda"),
                            Name = "Maverick",
                            Type = "Bird"
                        });
                });

            modelBuilder.Entity("Domain.Models.Animals.Birds.Bird", b =>
                {
                    b.Property<Guid>("BirdID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AnimalID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CanFly")
                        .HasColumnType("bit");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BirdID");

                    b.HasIndex("AnimalID");

                    b.ToTable("Birds");

                    b.HasData(
                        new
                        {
                            BirdID = new Guid("0303504c-ec24-401a-860c-1ac0ae9f12ff"),
                            CanFly = false,
                            Color = "Red",
                            Name = "Chip"
                        },
                        new
                        {
                            BirdID = new Guid("3deb994b-b559-40cf-8003-40d644fcfc8a"),
                            CanFly = true,
                            Color = "Blue",
                            Name = "Paulie"
                        },
                        new
                        {
                            BirdID = new Guid("6ccc4bd2-ff46-45ed-8a71-03a4318714e8"),
                            CanFly = true,
                            Color = "Orange",
                            Name = "Polly"
                        },
                        new
                        {
                            BirdID = new Guid("b18205d4-17ca-4233-93dd-8923154eeba4"),
                            CanFly = false,
                            Color = "Red",
                            Name = "Ace"
                        },
                        new
                        {
                            BirdID = new Guid("f1233b7a-ba0e-464f-8633-6ddcd45962b9"),
                            CanFly = false,
                            Color = "Green",
                            Name = "Apollo"
                        },
                        new
                        {
                            BirdID = new Guid("f56a5dc5-35df-4f8a-b255-294fbd812891"),
                            CanFly = true,
                            Color = "Green",
                            Name = "Daffy"
                        },
                        new
                        {
                            BirdID = new Guid("24dc68c6-6980-46f6-b23f-e3abccc0a0f1"),
                            CanFly = true,
                            Color = "Purple",
                            Name = "Blue"
                        },
                        new
                        {
                            BirdID = new Guid("221d53e4-1e0f-44a7-93a0-dd14dc8104b3"),
                            CanFly = false,
                            Color = "Yellow",
                            Name = "Skye"
                        },
                        new
                        {
                            BirdID = new Guid("2dbbd568-78e0-42ff-a675-bf268adf598e"),
                            CanFly = true,
                            Color = "Purple",
                            Name = "Jay"
                        },
                        new
                        {
                            BirdID = new Guid("7a50bfdc-e200-41e8-9769-e70f77147cda"),
                            CanFly = true,
                            Color = "Yellow",
                            Name = "Maverick"
                        });
                });

            modelBuilder.Entity("Domain.Models.Animals.Cats.Cat", b =>
                {
                    b.Property<Guid>("CatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AnimalID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LikesToPlay")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("CatID");

                    b.HasIndex("AnimalID");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            CatID = new Guid("01df08f7-f0e8-433b-aed0-c426ae257fcc"),
                            Breed = "Siames",
                            LikesToPlay = true,
                            Name = "Jack",
                            Weight = 3
                        },
                        new
                        {
                            CatID = new Guid("37a7f1e7-7c39-4a9f-a72b-d5022d61c021"),
                            Breed = "Ragdoll",
                            LikesToPlay = false,
                            Name = "Signe",
                            Weight = 4
                        },
                        new
                        {
                            CatID = new Guid("1e34fb48-58b3-4685-a38b-1b381fa07e22"),
                            Breed = "Bengal",
                            LikesToPlay = false,
                            Name = "Rose",
                            Weight = 6
                        },
                        new
                        {
                            CatID = new Guid("7da9bbfa-0ff4-4758-941b-55dedda0aca7"),
                            Breed = "Burma",
                            LikesToPlay = true,
                            Name = "Mittens",
                            Weight = 5
                        },
                        new
                        {
                            CatID = new Guid("dc1f1b5a-50ae-4b21-ba80-7919403d2634"),
                            Breed = "Brittiskt korthår",
                            LikesToPlay = true,
                            Name = "Fred",
                            Weight = 4
                        },
                        new
                        {
                            CatID = new Guid("2112ef42-3c65-400b-aa15-2891b4fbb6f0"),
                            Breed = "Ragdoll",
                            LikesToPlay = false,
                            Name = "Molly",
                            Weight = 6
                        },
                        new
                        {
                            CatID = new Guid("d0ddb4a7-9369-4b3f-9c2a-5b3e282235ef"),
                            Breed = "Perser",
                            LikesToPlay = true,
                            Name = "Charlie",
                            Weight = 3
                        },
                        new
                        {
                            CatID = new Guid("33d22b2d-db29-482a-9c87-225ab75592ed"),
                            Breed = "Burma",
                            LikesToPlay = true,
                            Name = "Oscar",
                            Weight = 4
                        },
                        new
                        {
                            CatID = new Guid("5cb27aea-7288-46a2-80dc-1715a6d35c29"),
                            Breed = "Perser",
                            LikesToPlay = false,
                            Name = "Tiger",
                            Weight = 5
                        },
                        new
                        {
                            CatID = new Guid("a4ba4856-b64b-4697-adde-516c9f856fa5"),
                            Breed = "Bengal",
                            LikesToPlay = true,
                            Name = "Simba",
                            Weight = 6
                        });
                });

            modelBuilder.Entity("Domain.Models.Animals.Dogs.Dog", b =>
                {
                    b.Property<Guid>("DogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AnimalID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("DogID");

                    b.HasIndex("AnimalID");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            DogID = new Guid("e7775aaf-f27c-469e-b17d-0c88590e1fc4"),
                            Breed = "Labrador",
                            Name = "OldG",
                            Weight = 10
                        },
                        new
                        {
                            DogID = new Guid("aa9cd7c2-a702-4658-a09a-5f4f622873e2"),
                            Breed = "Bulldog",
                            Name = "NewG",
                            Weight = 4
                        },
                        new
                        {
                            DogID = new Guid("dd622008-e534-46d2-8df8-6fa330f16ebb"),
                            Breed = "Schäfer",
                            Name = "Björn",
                            Weight = 12
                        },
                        new
                        {
                            DogID = new Guid("25925cfb-a43a-490d-852d-69f8a085d0fb"),
                            Breed = "Golden retriever",
                            Name = "Patrik",
                            Weight = 13
                        },
                        new
                        {
                            DogID = new Guid("d0278d8a-e841-4639-841a-4d9b5a5935de"),
                            Breed = "Pudel",
                            Name = "Alfred",
                            Weight = 6
                        },
                        new
                        {
                            DogID = new Guid("57bb1c98-5da1-4552-aa00-921bdb53e542"),
                            Breed = "Labrador",
                            Name = "Stanley",
                            Weight = 6
                        },
                        new
                        {
                            DogID = new Guid("753b16a5-479e-4528-a75d-5e98033cd0c1"),
                            Breed = "Rottweiler",
                            Name = "Rufus",
                            Weight = 8
                        },
                        new
                        {
                            DogID = new Guid("3d5fa03c-a75c-4eff-81c4-d0e1c7f82ff3"),
                            Breed = "Boxer",
                            Name = "Ludde",
                            Weight = 9
                        },
                        new
                        {
                            DogID = new Guid("5c65250c-21ae-4e92-b6b7-2a42f311edc3"),
                            Breed = "Labrador",
                            Name = "Felix",
                            Weight = 12
                        },
                        new
                        {
                            DogID = new Guid("f7b4f4ae-19d2-4fd6-bfcc-536921b3a867"),
                            Breed = "Boxer",
                            Name = "Peppe",
                            Weight = 8
                        });
                });

            modelBuilder.Entity("Domain.Models.Users.User", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Authorized")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = new Guid("10ba5986-c597-44a9-b87f-093d6c102ca2"),
                            Authorized = true,
                            Password = "admin",
                            Role = "admin",
                            Username = "admin"
                        },
                        new
                        {
                            ID = new Guid("12345678-1234-5678-1234-567812345674"),
                            Authorized = true,
                            Password = "password",
                            Role = "admin",
                            Username = "testUser2"
                        });
                });

            modelBuilder.Entity("Domain.Models.AnimalUsers.AnimalUser", b =>
                {
                    b.HasOne("Domain.Models.Animals.Animal", "Animal")
                        .WithMany("AnimalUsers")
                        .HasForeignKey("AnimalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Users.User", "User")
                        .WithMany("AnimalUsers")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.Animals.Birds.Bird", b =>
                {
                    b.HasOne("Domain.Models.Animals.Animal", null)
                        .WithMany("Birds")
                        .HasForeignKey("AnimalID");
                });

            modelBuilder.Entity("Domain.Models.Animals.Cats.Cat", b =>
                {
                    b.HasOne("Domain.Models.Animals.Animal", null)
                        .WithMany("Cats")
                        .HasForeignKey("AnimalID");
                });

            modelBuilder.Entity("Domain.Models.Animals.Dogs.Dog", b =>
                {
                    b.HasOne("Domain.Models.Animals.Animal", null)
                        .WithMany("Dogs")
                        .HasForeignKey("AnimalID");
                });

            modelBuilder.Entity("Domain.Models.Animals.Animal", b =>
                {
                    b.Navigation("AnimalUsers");

                    b.Navigation("Birds");

                    b.Navigation("Cats");

                    b.Navigation("Dogs");
                });

            modelBuilder.Entity("Domain.Models.Users.User", b =>
                {
                    b.Navigation("AnimalUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
