// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(RealDatabase))]
    partial class RealDatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.AnimalUsers.AnimalUser", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnimalID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Key");

                    b.HasIndex("AnimalID");

                    b.HasIndex("UserID");

                    b.ToTable("AnimalUsers");
                });

            modelBuilder.Entity("Domain.Models.Animals.Animal", b =>
                {
                    b.Property<Guid>("AnimalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnimalID");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalID = new Guid("f9562e70-45d3-4e4b-b4e5-4974fb47ba36"),
                            Name = "OldG",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalID = new Guid("27a1fd69-423f-42b3-9573-6914b33f717c"),
                            Name = "NewG",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalID = new Guid("c0497ba8-b715-406e-a8fe-bdc88b6d9096"),
                            Name = "Björn",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalID = new Guid("fba79c58-c875-4e4b-80b9-5e250bbebd52"),
                            Name = "Patrik",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalID = new Guid("f3ce2d2b-aae3-4aa3-a280-dae229e21aa4"),
                            Name = "Alfred",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalID = new Guid("65eb3f00-a585-4d73-bbd7-589c2f61e3de"),
                            Name = "Stanley",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalID = new Guid("c2ce0766-fe81-42dc-a957-5c5eeeec6b33"),
                            Name = "Rufus",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalID = new Guid("7d3e352a-3560-4df0-a03a-8131d7c53286"),
                            Name = "Ludde",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalID = new Guid("cb6cc4fe-52a6-47d3-a8df-6c1946b4090c"),
                            Name = "Felix",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalID = new Guid("999b246c-71c7-4008-b823-5dbcf7dc74c1"),
                            Name = "Peppe",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalID = new Guid("6cf2f038-545a-4106-aaeb-ef87708e2285"),
                            Name = "Jack",
                            Type = "Cat"
                        },
                        new
                        {
                            AnimalID = new Guid("7e1909ca-a291-4524-8d79-cbdc3519a805"),
                            Name = "Signe",
                            Type = "Cat"
                        },
                        new
                        {
                            AnimalID = new Guid("139121c5-e18a-4e66-a613-820ab065c915"),
                            Name = "Rose",
                            Type = "Cat"
                        },
                        new
                        {
                            AnimalID = new Guid("f6b83270-68e9-45ec-82b7-4e8b700eb70b"),
                            Name = "Mittens",
                            Type = "Cat"
                        },
                        new
                        {
                            AnimalID = new Guid("b5657528-7eb6-4068-b55a-f54ac1a61fb6"),
                            Name = "Fred",
                            Type = "Cat"
                        },
                        new
                        {
                            AnimalID = new Guid("2f0fb393-fc1e-481c-8e41-fc90b258711e"),
                            Name = "Molly",
                            Type = "Cat"
                        },
                        new
                        {
                            AnimalID = new Guid("6951237d-24e9-46ad-a5fa-525d3f005e66"),
                            Name = "Charlie",
                            Type = "Cat"
                        },
                        new
                        {
                            AnimalID = new Guid("a9a96751-a9bb-4124-ba32-152d57534ded"),
                            Name = "Oscar",
                            Type = "Cat"
                        },
                        new
                        {
                            AnimalID = new Guid("045d4182-cd28-401d-be8b-007abb2d9105"),
                            Name = "Tiger",
                            Type = "Cat"
                        },
                        new
                        {
                            AnimalID = new Guid("a9554639-2d39-4054-97c1-5f444b3a3c8d"),
                            Name = "Simba",
                            Type = "Cat"
                        },
                        new
                        {
                            AnimalID = new Guid("ef4c76ca-ae86-4276-a764-c0d33da81c6c"),
                            Name = "Chip",
                            Type = "Bird"
                        },
                        new
                        {
                            AnimalID = new Guid("f56b6393-4fab-4f94-bee5-4783d28b70de"),
                            Name = "Paulie",
                            Type = "Bird"
                        },
                        new
                        {
                            AnimalID = new Guid("18951cee-1f2c-4a7e-be9e-1c04f4184902"),
                            Name = "Polly",
                            Type = "Bird"
                        },
                        new
                        {
                            AnimalID = new Guid("e00cff79-927b-451a-ba9c-406c42635be2"),
                            Name = "Ace",
                            Type = "Bird"
                        },
                        new
                        {
                            AnimalID = new Guid("48635346-a311-4a4c-9410-c4f55e304dd9"),
                            Name = "Apollo",
                            Type = "Bird"
                        },
                        new
                        {
                            AnimalID = new Guid("69b059b7-c4c8-4ba4-b6ec-4bd9b79a7535"),
                            Name = "Daffy",
                            Type = "Bird"
                        },
                        new
                        {
                            AnimalID = new Guid("9e9b684d-b5a1-4388-81f7-d079bdffadaa"),
                            Name = "Blue",
                            Type = "Bird"
                        },
                        new
                        {
                            AnimalID = new Guid("553f3872-dc38-4d24-b63f-7dc747cbd85c"),
                            Name = "Skye",
                            Type = "Bird"
                        },
                        new
                        {
                            AnimalID = new Guid("b0f9c05d-f617-4297-8a18-5f5670802f8a"),
                            Name = "Jay",
                            Type = "Bird"
                        },
                        new
                        {
                            AnimalID = new Guid("09898173-fd9d-48ab-84ca-a8050a543a95"),
                            Name = "Maverick",
                            Type = "Bird"
                        });
                });

            modelBuilder.Entity("Domain.Models.Animals.Birds.Bird", b =>
                {
                    b.Property<Guid>("BirdID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AnimalID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CanFly")
                        .HasColumnType("bit");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BirdID");

                    b.HasIndex("AnimalID");

                    b.ToTable("Birds");

                    b.HasData(
                        new
                        {
                            BirdID = new Guid("ef4c76ca-ae86-4276-a764-c0d33da81c6c"),
                            CanFly = false,
                            Color = "",
                            Name = "Chip"
                        },
                        new
                        {
                            BirdID = new Guid("f56b6393-4fab-4f94-bee5-4783d28b70de"),
                            CanFly = false,
                            Color = "",
                            Name = "Paulie"
                        },
                        new
                        {
                            BirdID = new Guid("18951cee-1f2c-4a7e-be9e-1c04f4184902"),
                            CanFly = false,
                            Color = "",
                            Name = "Polly"
                        },
                        new
                        {
                            BirdID = new Guid("e00cff79-927b-451a-ba9c-406c42635be2"),
                            CanFly = false,
                            Color = "",
                            Name = "Ace"
                        },
                        new
                        {
                            BirdID = new Guid("48635346-a311-4a4c-9410-c4f55e304dd9"),
                            CanFly = false,
                            Color = "",
                            Name = "Apollo"
                        },
                        new
                        {
                            BirdID = new Guid("69b059b7-c4c8-4ba4-b6ec-4bd9b79a7535"),
                            CanFly = false,
                            Color = "",
                            Name = "Daffy"
                        },
                        new
                        {
                            BirdID = new Guid("9e9b684d-b5a1-4388-81f7-d079bdffadaa"),
                            CanFly = false,
                            Color = "",
                            Name = "Blue"
                        },
                        new
                        {
                            BirdID = new Guid("553f3872-dc38-4d24-b63f-7dc747cbd85c"),
                            CanFly = false,
                            Color = "",
                            Name = "Skye"
                        },
                        new
                        {
                            BirdID = new Guid("b0f9c05d-f617-4297-8a18-5f5670802f8a"),
                            CanFly = false,
                            Color = "",
                            Name = "Jay"
                        },
                        new
                        {
                            BirdID = new Guid("09898173-fd9d-48ab-84ca-a8050a543a95"),
                            CanFly = false,
                            Color = "",
                            Name = "Maverick"
                        });
                });

            modelBuilder.Entity("Domain.Models.Animals.Cats.Cat", b =>
                {
                    b.Property<Guid>("CatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AnimalID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LikesToPlay")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("CatID");

                    b.HasIndex("AnimalID");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            CatID = new Guid("6cf2f038-545a-4106-aaeb-ef87708e2285"),
                            Breed = "",
                            LikesToPlay = false,
                            Name = "Jack",
                            Weight = 0
                        },
                        new
                        {
                            CatID = new Guid("7e1909ca-a291-4524-8d79-cbdc3519a805"),
                            Breed = "",
                            LikesToPlay = false,
                            Name = "Signe",
                            Weight = 0
                        },
                        new
                        {
                            CatID = new Guid("139121c5-e18a-4e66-a613-820ab065c915"),
                            Breed = "",
                            LikesToPlay = false,
                            Name = "Rose",
                            Weight = 0
                        },
                        new
                        {
                            CatID = new Guid("f6b83270-68e9-45ec-82b7-4e8b700eb70b"),
                            Breed = "",
                            LikesToPlay = false,
                            Name = "Mittens",
                            Weight = 0
                        },
                        new
                        {
                            CatID = new Guid("b5657528-7eb6-4068-b55a-f54ac1a61fb6"),
                            Breed = "",
                            LikesToPlay = false,
                            Name = "Fred",
                            Weight = 0
                        },
                        new
                        {
                            CatID = new Guid("2f0fb393-fc1e-481c-8e41-fc90b258711e"),
                            Breed = "",
                            LikesToPlay = false,
                            Name = "Molly",
                            Weight = 0
                        },
                        new
                        {
                            CatID = new Guid("6951237d-24e9-46ad-a5fa-525d3f005e66"),
                            Breed = "",
                            LikesToPlay = false,
                            Name = "Charlie",
                            Weight = 0
                        },
                        new
                        {
                            CatID = new Guid("a9a96751-a9bb-4124-ba32-152d57534ded"),
                            Breed = "",
                            LikesToPlay = false,
                            Name = "Oscar",
                            Weight = 0
                        },
                        new
                        {
                            CatID = new Guid("045d4182-cd28-401d-be8b-007abb2d9105"),
                            Breed = "",
                            LikesToPlay = false,
                            Name = "Tiger",
                            Weight = 0
                        },
                        new
                        {
                            CatID = new Guid("a9554639-2d39-4054-97c1-5f444b3a3c8d"),
                            Breed = "",
                            LikesToPlay = false,
                            Name = "Simba",
                            Weight = 0
                        });
                });

            modelBuilder.Entity("Domain.Models.Animals.Dogs.Dog", b =>
                {
                    b.Property<Guid>("DogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AnimalID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("DogID");

                    b.HasIndex("AnimalID");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            DogID = new Guid("f9562e70-45d3-4e4b-b4e5-4974fb47ba36"),
                            Breed = "",
                            Name = "OldG",
                            Weight = 0
                        },
                        new
                        {
                            DogID = new Guid("27a1fd69-423f-42b3-9573-6914b33f717c"),
                            Breed = "",
                            Name = "NewG",
                            Weight = 0
                        },
                        new
                        {
                            DogID = new Guid("c0497ba8-b715-406e-a8fe-bdc88b6d9096"),
                            Breed = "",
                            Name = "Björn",
                            Weight = 0
                        },
                        new
                        {
                            DogID = new Guid("fba79c58-c875-4e4b-80b9-5e250bbebd52"),
                            Breed = "",
                            Name = "Patrik",
                            Weight = 0
                        },
                        new
                        {
                            DogID = new Guid("f3ce2d2b-aae3-4aa3-a280-dae229e21aa4"),
                            Breed = "",
                            Name = "Alfred",
                            Weight = 0
                        },
                        new
                        {
                            DogID = new Guid("65eb3f00-a585-4d73-bbd7-589c2f61e3de"),
                            Breed = "",
                            Name = "Stanley",
                            Weight = 0
                        },
                        new
                        {
                            DogID = new Guid("c2ce0766-fe81-42dc-a957-5c5eeeec6b33"),
                            Breed = "",
                            Name = "Rufus",
                            Weight = 0
                        },
                        new
                        {
                            DogID = new Guid("7d3e352a-3560-4df0-a03a-8131d7c53286"),
                            Breed = "",
                            Name = "Ludde",
                            Weight = 0
                        },
                        new
                        {
                            DogID = new Guid("cb6cc4fe-52a6-47d3-a8df-6c1946b4090c"),
                            Breed = "",
                            Name = "Felix",
                            Weight = 0
                        },
                        new
                        {
                            DogID = new Guid("999b246c-71c7-4008-b823-5dbcf7dc74c1"),
                            Breed = "",
                            Name = "Peppe",
                            Weight = 0
                        });
                });

            modelBuilder.Entity("Domain.Models.Users.User", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Authorized")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = new Guid("9cf8a602-0159-440a-94a0-3849a3f90424"),
                            Authorized = true,
                            Password = "admin",
                            Role = "admin",
                            Username = "admin"
                        },
                        new
                        {
                            ID = new Guid("12345678-1234-5678-1234-567812345674"),
                            Authorized = true,
                            Password = "password",
                            Role = "admin",
                            Username = "testUser2"
                        });
                });

            modelBuilder.Entity("Domain.Models.AnimalUsers.AnimalUser", b =>
                {
                    b.HasOne("Domain.Models.Animals.Animal", "Animal")
                        .WithMany("AnimalUsers")
                        .HasForeignKey("AnimalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Users.User", "User")
                        .WithMany("AnimalUsers")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.Animals.Birds.Bird", b =>
                {
                    b.HasOne("Domain.Models.Animals.Animal", null)
                        .WithMany("Birds")
                        .HasForeignKey("AnimalID");
                });

            modelBuilder.Entity("Domain.Models.Animals.Cats.Cat", b =>
                {
                    b.HasOne("Domain.Models.Animals.Animal", null)
                        .WithMany("Cats")
                        .HasForeignKey("AnimalID");
                });

            modelBuilder.Entity("Domain.Models.Animals.Dogs.Dog", b =>
                {
                    b.HasOne("Domain.Models.Animals.Animal", null)
                        .WithMany("Dogs")
                        .HasForeignKey("AnimalID");
                });

            modelBuilder.Entity("Domain.Models.Animals.Animal", b =>
                {
                    b.Navigation("AnimalUsers");

                    b.Navigation("Birds");

                    b.Navigation("Cats");

                    b.Navigation("Dogs");
                });

            modelBuilder.Entity("Domain.Models.Users.User", b =>
                {
                    b.Navigation("AnimalUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
